### ISSUE TITLE
🐛 [Bug] pre-commit 적용시 발생한 에러 - [WinError 5] 

### ISSUE THREAD

**Issue by kyeon06** [kyeon06/django-sample-project#10]
## Describe the bug
black 포맷터 적용시 계속 엑세스 거부가 발생
```
[WinError 5] 엑세스가 거부되었습니다.
```
## Attachment
![image](https://github.com/kyeon06/django-sample-project/assets/111492415/50b8443e-ed94-4ad8-94c1-ec1528151f89)

**Comment by kyeon06** [comment]
## Describe the bug
pre-commit-config.yaml 파일에서 black부분을 아래와 같이 변경했을 경우 발생
```
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
 ```

> [ImportError: cannot import name '_unicodefun' from 'click'](https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click)

## Attachment
![image](https://github.com/kyeon06/django-sample-project/assets/111492415/523ac92d-3b8e-4dd5-955c-717b361f6057)

**Comment by kyeon06** [comment]
```
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
```

최종 위와 같이 변경했을 경우 잘 실행되는 것으로 확인
